main: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta
run_case1: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 -Drun1 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta1
run_case2: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 -Drun2 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta2
run_case3: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 -Drun3 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta3
run_case4: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 -Drun4 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta4
run_case5: main.cpp cirMgr.cpp Gate.cpp Path.cpp 
	g++ -O2 -Drun5 main.cpp cirMgr.cpp Gate.cpp Path.cpp -o run_sta5
clean:
	rm run_*
